#!/usr/bin/env ruby

HINSHI_ATOK2MSIME = {
  'カ行五段' => 'か行五段',
  'ガ行五段' => 'が行五段',
  'サ変動詞' => 'さ変動詞',
  'サ行五段' => 'さ行五段',
  'ザ変動詞' => 'ざ変動詞',
  'タ行五段' => 'た行五段',
  'ナ行五段' => 'な行五段',
  'バ行五段' => 'ば行五段',
  'マ行五段' => 'ま行五段',
  'ラ行五段' => 'ら行五段',
  'ワ行五段' => 'あわ行五段',
  '一段動詞' => '一段動詞',
  '冠数詞' => '冠数詞',
  '副詞' => '副詞',
  '助数詞' => '助数詞',
  '単漢字' => '単漢字',
  '名詞' => '名詞',
  '名詞形動' => '形容動詞',
  '名詞サ変' => 'さ変名詞',
  '名詞ザ変' => 'ざ変名詞',
  '固有一般' => '固有名詞',
  '固有人名' => '名',
  '固有人姓' => '姓',
  '固有商品' => '固有名詞',
  '固有地名' => '地名その他',
  '固有組織' => '社名',
  '形動タリ' => '形容動詞タル',
  '形容動詞' => '形容動詞',
  '形容詞' => '形容詞',
  '感動詞' => '感動詞',
  '接尾語' => '接尾語',
  '接続詞' => '接続詞',
  '接頭語' => '接頭語',
  '数詞' => '数量',
  '独立語' => '独立語',
  '短縮読み' => '短縮よみ',
  '連体詞' => '連体詞',
  '顔文字' => '顔文字',
}

def convert_atok_file(file)
  open_input(file) do |io|
    io.each_line(chomp: true) do |line|
      case line
      when /\A\s*\z|\A!!ATOK_TANGO_TEXT_HEADER_1\z/
        next
      when /\A!!(\s.*\z)?/
        puts "!#{$1}"
        next
      end

      yomi, tango, hinshi = line.split(/\t+/)
      next if hinshi.nil?

      hinshi = hinshi.sub(/[*$]+\z/, "")
      newhinshi = HINSHI_ATOK2MSIME[hinshi] or
        raise "unsupported hinshi"

      puts [yomi, tango, newhinshi].join("\t")
    rescue => e
      warn "skipped: %s %s [%s]: #{e}" % [yomi, tango, hinshi]
    end
  end
end

def open_input(file)
  if file == "-"
    setup_input(STDIN)
    yield STDIN
  else
    File.open(file, "rb") do |io|
      setup_input(io)
      yield io
    end
  end
end

def setup_input(io)
  io.binmode
  if (encoding = io.set_encoding_by_bom)
    io.set_encoding(encoding, Encoding::UTF_8)
  else
    io.set_encoding(Encoding::UTF_8)
  end
end

$stdout.set_encoding(Encoding::UTF_16LE, Encoding::UTF_8, crlf_newline: true)
$stdout.write("\uFEFF")

puts "!Microsoft IME Dictionary Tool",
  "!Version:",
  "!Format:WORDLIST",
  "!DateTime: #{Time.now.strftime("%Y年%m月%d日")}",
  ""

files = ARGV.empty? ? ["-"] : ARGV

files.each do |file|
  convert_atok_file(file)
end
