#!/usr/bin/env ruby

HINSHI_MSIME2ATOK = {
  "か行五段" => "カ行五段",
  "が行五段" => "ガ行五段",
  "さ変動詞" => "サ変動詞",
  "さ行五段" => "サ行五段",
  "ざ変動詞" => "ザ変動詞",
  "た行五段" => "タ行五段",
  "な行五段" => "ナ行五段",
  "ば行五段" => "バ行五段",
  "ま行五段" => "マ行五段",
  "ら行五段" => "ラ行五段",
  "あわ行五段" => "ワ行五段",
  "わ行五段" => "ワ行五段",
  "一段動詞" => "一段動詞",
  "冠数詞" => "冠数詞",
  "副詞" => "副詞",
  "助数詞" => "助数詞",
  "単漢字" => "単漢字",
  "名詞" => "名詞",
  "形容動詞" => "形容動詞",
  "さ変名詞" => "名詞サ変",
  "ざ変名詞" => "名詞ザ変",
  "固有名詞" => "固有一般",
  "名" => "固有人名",
  "姓" => "固有人姓",
  "地名その他" => "固有地名",
  "社名" => "固有組織",
  "形容動詞タル" => "形動タリ",
  "形容詞" => "形容詞",
  "感動詞" => "感動詞",
  "接尾語" => "接尾語",
  "接続詞" => "接続詞",
  "接頭語" => "接頭語",
  "数量" => "数詞",
  "独立語" => "独立語",
  "短縮よみ" => "短縮読み",
  "連体詞" => "連体詞",
  "顔文字" => "顔文字",
}

def each_msime_line(file, &block)
  open_input(file) do |io|
    io.each_line(chomp: true, &block)
  end
end

def open_input(file)
  if file == "-"
    setup_input(STDIN)
    yield STDIN
  else
    File.open(file, "rb") do |io|
      setup_input(io)
      yield io
    end
  end
end

def setup_input(io)
  io.binmode
  if (encoding = io.set_encoding_by_bom)
    io.set_encoding(encoding, Encoding::UTF_8)
  else
    io.set_encoding(Encoding::UTF_8)
  end
end

def convert_msime_file(file)
  each_msime_line(file) do |line|
    case line
    when /\A\s*\z|\A!\S/
      next
    when /\A!(\s.*\z)?/
      puts "!!#{$1}"
      next
    end

    yomi, tango, hinshi = line.split(/\t+/)
    next if hinshi.nil?

    hinshi = hinshi.sub(/[*$]+\z/, "")
    newhinshi = HINSHI_MSIME2ATOK[hinshi] or
      raise "unsupported hinshi"

    puts [yomi, tango, "#{newhinshi}*"].join("\t")
  rescue => e
    warn "skipped: %s %s [%s]: #{e}" % [yomi, tango, hinshi]
  end
end

$stdout.set_encoding(Encoding::UTF_8, Encoding::UTF_8, crlf_newline: true)

puts "!!ATOK_TANGO_TEXT_HEADER_1"

files = ARGV.empty? ? ["-"] : ARGV

files.each do |file|
  convert_msime_file(file)
end
